### ISSUE TITLE
Duplicate zip entry 

### ISSUE THREAD

**Issue by felipeaugusto1** [loopme/loopme-android-sdk#5]
`(Duplicate zip entry [classes.jar:com/google/android/gms/internal/zzarq.class]))`

How can I fix that error? It happens when trying to generate an APK with proguard.

**Comment by katrin010692** [comment]
Hi, Felipe. You should add to your proguard-rules.pro

-keep class com.google.android.gms.* { ; }
-dontwarn com.google.android.gms.**

And if you're using dependency to com.google.android.gms:play-services-ads, you should remove it, cause loopme-sdk already contains it.

Thank you.

**Comment by felipeaugusto1** [comment]
Hi, yes. I use com.google.android.gms:play-services-ad to be able to use AdMob. If I take it out, AdMob doesn't work anymore. What version is in loopme-sdk?
