### ISSUE TITLE
Multidex issue

### ISSUE THREAD

**Issue by felipeaugusto1** [loopme/loopme-android-sdk#7]
Hi, I have updated the loopme sdk to version 5.1.16, and it has fixed the play-services-ads bug. But now, the same error is happening for MultiDex. Even removing the dependency (compile 'com.android.support:multidex:1.0.1'), I get the error of duplicated zip entry for multidex class.

**Comment by drewster99** [comment]
Confirmed - same here.

**Comment by katrin010692** [comment]
Fixed in version 5.1.17. 

Thank you
