### ISSUE TITLE
LoopMeInterstitial.load() is unacceptably slow

### ISSUE THREAD

**Issue by drewster99** [loopme/loopme-android-sdk#8]
Calling the load() method of LoopMeInterstitial typically is an unacceptably long call -- typically 2000 to 3000ms (**2 to 3 seconds**) in our tests (measured with SystemClock.uptimeMillis()).  This hangs the UI thread of the app during the call, causing a high amount of Slow Rendering and Frozen Frames in the Google Play Developer Console, as well as user complaints.

By comparison, all other ad networks complete their "load" calls within 50ms _combined_.

We tried moving this call to a background thread, but this causes a crash just after the ad is dismissed.

**Comment by katrin010692** [comment]
Hi, this issue was fixed in the latest version of sdk. Please, update loopme-sdk version (5.1.8)
