### ISSUE TITLE
java.lang.NoSuchMethodError: No static method getInstance(Ljava/lang/String;Landroid/content/Context;)Lcom/loopme/LoopMeInterstitial

### ISSUE THREAD

**Issue by drewster99** [loopme/loopme-android-sdk#9]
Updating from 5.1.11, it's not finding **LoopMeInterstitial.getInstance()**.  

Error output:

    09-15 11:42:43.004 10885 10885 D AndroidRuntime: Shutting down VM
    09-15 11:42:43.004 10885 10885 W System.err: java.lang.NoSuchMethodError: No static method getInstance(Ljava/lang/String;Landroid/content/Context;)Lcom/loopme/LoopMeInterstitial; in class Lcom/loopme/LoopMeInterstitial; or its super classes (declaration of 'com.loopme.LoopMeInterstitial' appears in /data/app/com.mycompany.mygame-1/base.apk:classes3.dex)
    09-15 11:42:43.004 10885 10885 W System.err:        at com.mycompany.adsystem.MyAdsLoopme.initialise(MyAdsLoopme.java:32)
    09-15 11:42:43.004 10885 10885 W System.err:        at com.mycompany.adsystem.MyAds.initialiseAdNetworks(MyAds.java:1493)
    09-15 11:42:43.004 10885 10885 W System.err:        at com.mycompany.adsystem.MyAds.access$900(MyAds.java:54)
    09-15 11:42:43.004 10885 10885 W System.err:        at com.mycompany.adsystem.MyAds$AdsJsonTask.onPostExecute(MyAds.java:2796)
    09-15 11:42:43.004 10885 10885 W System.err:        at com.mycompany.adsystem.MyAds$AdsJsonTask.onPostExecute(MyAds.java:2692)
    09-15 11:42:43.004 10885 10885 W System.err:        at android.os.AsyncTask.finish(AsyncTask.java:651)
    09-15 11:42:43.004 10885 10885 W System.err:        at android.os.AsyncTask.access$500(AsyncTask.java:180)
    09-15 11:42:43.004 10885 10885 W System.err:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
    09-15 11:42:43.004 10885 10885 W System.err:        at android.os.Handler.dispatchMessage(Handler.java:102)
    09-15 11:42:43.004 10885 10885 W System.err:        at android.os.Looper.loop(Looper.java:148)
    09-15 11:42:43.004 10885 10885 W System.err:        at android.app.ActivityThread.main(ActivityThread.java:7223)
    09-15 11:42:43.004 10885 10885 W System.err:        at java.lang.reflect.Method.invoke(Native Method)
    09-15 11:42:43.004 10885 10885 W System.err:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    09-15 11:42:43.004 10885 10885 W System.err:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Dependency:

    compile 'com.loopme:loopme-sdk:5.1.18@aar'

Switching back to 5.1.11 and error goes away:

    'com.loopme:loopme-sdk:5.1.11@aar'

Code snippet:

    private LoopMeInterstitial mInterstitial;
    private Activity mActivity;

    public void initialise(Context context, Activity activity) {
        mActivity = activity;
        mInterstitial = LoopMeInterstitial.getInstance(appId, mActivity); // <-- FAILING HERE
        mInterstitial.setListener(this);
    }

Both release and debug have the same behavior.

**Comment by katrin010692** [comment]
Method getInstance(appKey, activity) didn't change since version 5.1.11. 
https://github.com/loopme/loopme-android-sdk/blob/master/loopme-sdk/src/main/java/com/loopme/LoopMeInterstitial.java

Please, try clean/build your project
